services:
  backend:
    build:
      context: ./api
    ports:
      - "18080:18080"
      - "18081:18081"
    volumes:
      - ./api/https:/https:ro
    working_dir: /src/N5.Challenge.WebApi
    command:
      [
        "dotnet", "watch", "run",
        "--urls", "http://0.0.0.0:18080;https://0.0.0.0:18081",
        "--launch-profile", "Docker"
      ]
    environment:
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password123
      - KAFKA__BOOTSTRAP_SERVERS=kafka:19092
    depends_on:
      - sqlserver
      - elasticsearch
      - kafka
    networks:
      - challenge-net

  frontend:
    build:
      context: ./app
    ports:
      - "13000:5173"
    volumes:
      - ./app/src:/app/src
      - ./app/public:/app/public
      - ./app/vite.config.js:/app/vite.config.js
    working_dir: /app
    depends_on:
      - backend
    networks:
      - challenge-net

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    ports:
      - "11433:1433"
    networks:
      - challenge-net

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "19200:9200"
    networks:
      - challenge-net

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "12181:2181"
    networks:
      - challenge-net

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ZOOKEEPER_CONNECTION_TIMEOUT_MS: 60000
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:19092,PLAINTEXT_HOST://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:19092,PLAINTEXT_HOST://localhost:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "19092:19092"
      - "29092:29092"
    networks:
      - challenge-net

volumes:
  nuget-packages:
  build-cache-bin:
  build-cache-obj:

networks:
  challenge-net: